### ISSUE TITLE
issues when i use any command like rank command or profile command

### ISSUE THREAD

**Issue by FastG4mer** [iAsure/discord-arts#18]
Error: invalid json response body at https://discord-arts.asure.dev/user/671005818287685644 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
at fetchUserData (C:\Users\Administrator\Desktop\GalaxyBot\node_modules\discord-arts\src\utils\fetch.utils.js:16:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async profileImage (C:\Users\Administrator\Desktop\GalaxyBot\node_modules\discord-arts\src\cards\profile-image.js:12:16)
at async Object.execute (C:\Users\Administrator\Desktop\GalaxyBot\src\events\ranking-system.js:83:22)

**Comment by Oliver-Turp** [comment]
I'm getting that same issue today. Hasn't happened before and no code has changed on this in a while.

**Comment by iAsure** [comment]
@FastG4mer @Oliver-Turp  Fixed! `npm i discord-arts@latest`
